export const NEW_PRODUCT_REQUEST= "NEW_PRODUCT_REQUEST"
export const NEW_PRODUCT_SUCCESS= "NEW_PRODUCT_SUCCESS"
export const NEW_PRODUCT_FAIL= "NEW_PRODUCT_FAIL"
export const NEW_PRODUCT_RESET= "NEW_PRODUCT_RESET"

export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCEESS="GET_PRODUCTS_SUCEESS"
export const GET_PRODUCTS_FAIL= "GET_PRODUCTS_FAIL"

export const GET_SINGLE_PRODUCT_REQUEST= "GET_SINGLE_PRODUCT_REQUEST"
export const GET_SINGLE_PRODUCT_SUCESS= "GET_SINGLE_PRODUCT_SUCESS"
export const GET_SINGLE_PRODUCT_FAIL= "GET_SINGLE_PRODUCT_FAIL"

export const UPDATE_PRODUCT_REQUEST="UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAIL="UPDATE_PRODUCT_FAIL"
export const UPDATE_PRODUCT_RESET="UPDATE_PRODUCT_RESET"

export const DELETE_PRODUCT_REQUEST="DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL="DELETE_PRODUCT_FAIL"
export const DELETE_PRODUCT_RESET="DELETE_PRODUCT_RESET"

export const CLEAR_ERRORS="CLEAR_ERRORS"